apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sec-pod
  name: sec-pod
spec:
  containers:
  - image: nginx:1.25
    name: sec-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
